import subprocess

timeout_exception = subprocess.TimeoutExpired

process_exception = subprocess.CalledProcessError
